<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class LevelAmountTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        $silver_uuid  = DB::table('levels')->where('key', 'silver')->first()->uuid;
        $gold_uuid    = DB::table('levels')->where('key', 'gold')->first()->uuid;
        $diamond_uuid = DB::table('levels')->where('key', 'diamond')->first()->uuid;
        DB::table('level_amounts')->insert([
            // Level Silver
            [
                'uuid'       => Str::uuid(),
                'level_uuid' => $silver_uuid,
                'amount'     => 10,
                'available'  => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid'       => Str::uuid(),
                'level_uuid' => $silver_uuid,
                'amount'     => 15,
                'available'  => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid'       => Str::uuid(),
                'level_uuid' => $silver_uuid,
                'amount'     => 20,
                'available'  => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid'       => Str::uuid(),
                'level_uuid' => $silver_uuid,
                'amount'     => 25,
                'available'  => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid'       => Str::uuid(),
                'level_uuid' => $silver_uuid,
                'amount'     => 30,
                'available'  => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid'       => Str::uuid(),
                'level_uuid' => $silver_uuid,
                'amount'     => 35,
                'available'  => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid'       => Str::uuid(),
                'level_uuid' => $silver_uuid,
                'amount'     => 40,
                'available'  => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid'       => Str::uuid(),
                'level_uuid' => $silver_uuid,
                'amount'     => 45,
                'available'  => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Gold
            [
                'uuid'       => Str::uuid(),
                'level_uuid' => $gold_uuid,
                'amount'     => 15,
                'available'  => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid'       => Str::uuid(),
                'level_uuid' => $gold_uuid,
                'amount'     => 20,
                'available'  => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid'       => Str::uuid(),
                'level_uuid' => $gold_uuid,
                'amount'     => 25,
                'available'  => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid'       => Str::uuid(),
                'level_uuid' => $gold_uuid,
                'amount'     => 30,
                'available'  => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid'       => Str::uuid(),
                'level_uuid' => $gold_uuid,
                'amount'     => 35,
                'available'  => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid'       => Str::uuid(),
                'level_uuid' => $gold_uuid,
                'amount'     => 40,
                'available'  => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid'       => Str::uuid(),
                'level_uuid' => $gold_uuid,
                'amount'     => 45,
                'available'  => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid'       => Str::uuid(),
                'level_uuid' => $gold_uuid,
                'amount'     => 50,
                'available'  => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid'       => Str::uuid(),
                'level_uuid' => $gold_uuid,
                'amount'     => 60,
                'available'  => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid'       => Str::uuid(),
                'level_uuid' => $gold_uuid,
                'amount'     => 70,
                'available'  => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid'       => Str::uuid(),
                'level_uuid' => $gold_uuid,
                'amount'     => 80,
                'available'  => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid'       => Str::uuid(),
                'level_uuid' => $gold_uuid,
                'amount'     => 90,
                'available'  => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Diamond
            [
                'uuid'       => Str::uuid(),
                'level_uuid' => $diamond_uuid,
                'amount'     => 15,
                'available'  => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid'       => Str::uuid(),
                'level_uuid' => $diamond_uuid,
                'amount'     => 20,
                'available'  => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid'       => Str::uuid(),
                'level_uuid' => $diamond_uuid,
                'amount'     => 25,
                'available'  => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid'       => Str::uuid(),
                'level_uuid' => $diamond_uuid,
                'amount'     => 30,
                'available'  => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid'       => Str::uuid(),
                'level_uuid' => $diamond_uuid,
                'amount'     => 35,
                'available'  => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid'       => Str::uuid(),
                'level_uuid' => $diamond_uuid,
                'amount'     => 40,
                'available'  => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid'       => Str::uuid(),
                'level_uuid' => $diamond_uuid,
                'amount'     => 45,
                'available'  => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid'       => Str::uuid(),
                'level_uuid' => $diamond_uuid,
                'amount'     => 50,
                'available'  => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid'       => Str::uuid(),
                'level_uuid' => $diamond_uuid,
                'amount'     => 60,
                'available'  => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid'       => Str::uuid(),
                'level_uuid' => $diamond_uuid,
                'amount'     => 70,
                'available'  => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid'       => Str::uuid(),
                'level_uuid' => $diamond_uuid,
                'amount'     => 80,
                'available'  => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid'       => Str::uuid(),
                'level_uuid' => $diamond_uuid,
                'amount'     => 90,
                'available'  => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid'       => Str::uuid(),
                'level_uuid' => $diamond_uuid,
                'amount'     => 100,
                'available'  => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid'       => Str::uuid(),
                'level_uuid' => $diamond_uuid,
                'amount'     => 110,
                'available'  => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid'       => Str::uuid(),
                'level_uuid' => $diamond_uuid,
                'amount'     => 120,
                'available'  => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid'       => Str::uuid(),
                'level_uuid' => $diamond_uuid,
                'amount'     => 130,
                'available'  => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid'       => Str::uuid(),
                'level_uuid' => $diamond_uuid,
                'amount'     => 140,
                'available'  => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid'       => Str::uuid(),
                'level_uuid' => $diamond_uuid,
                'amount'     => 150,
                'available'  => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid'       => Str::uuid(),
                'level_uuid' => $diamond_uuid,
                'amount'     => 160,
                'available'  => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
